### ISSUE TITLE
README

### ISSUE THREAD

**Issue by sabiharustam** [sabiharustam/Voltcycle#3]
Update README.

- [x] Add logo ( Also include the reference for the pictures at the bottom)

- [x] Description of the TOOL

- [x] Organization of the project

- [x] Layout Future blocks

**Comment by kaykrish** [comment]
Here are the references for the images:
https://www.fotolia.com/id/209712729
https://www.youtube.com/watch?v=3l1hJzUqi2A
Where do you want me to add them?
@sabiharustam

**Comment by sabiharustam** [comment]
I can add them while editing README file. Thanks!
